/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects/$id/index'
import { Route as ProjectsIdSprintsIndexRouteImport } from './routes/projects/$id/sprints/index'
import { Route as ProjectsIdSettingsIndexRouteImport } from './routes/projects/$id/settings/index'
import { Route as ProjectsIdSprintsSprintIdIndexRouteImport } from './routes/projects/$id/sprints/$sprintId/index'
import { Route as ProjectsIdSettingsTemplatesIndexRouteImport } from './routes/projects/$id/settings/templates/index'
import { Route as ProjectsIdItemsItemIdIndexRouteImport } from './routes/projects/$id/items/$itemId/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdSprintsIndexRoute = ProjectsIdSprintsIndexRouteImport.update({
  id: '/projects/$id/sprints/',
  path: '/projects/$id/sprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdSettingsIndexRoute = ProjectsIdSettingsIndexRouteImport.update({
  id: '/projects/$id/settings/',
  path: '/projects/$id/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdSprintsSprintIdIndexRoute =
  ProjectsIdSprintsSprintIdIndexRouteImport.update({
    id: '/projects/$id/sprints/$sprintId/',
    path: '/projects/$id/sprints/$sprintId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdSettingsTemplatesIndexRoute =
  ProjectsIdSettingsTemplatesIndexRouteImport.update({
    id: '/projects/$id/settings/templates/',
    path: '/projects/$id/settings/templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdItemsItemIdIndexRoute =
  ProjectsIdItemsItemIdIndexRouteImport.update({
    id: '/projects/$id/items/$itemId/',
    path: '/projects/$id/items/$itemId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/settings/': typeof ProjectsIdSettingsIndexRoute
  '/projects/$id/sprints/': typeof ProjectsIdSprintsIndexRoute
  '/projects/$id/items/$itemId/': typeof ProjectsIdItemsItemIdIndexRoute
  '/projects/$id/settings/templates/': typeof ProjectsIdSettingsTemplatesIndexRoute
  '/projects/$id/sprints/$sprintId/': typeof ProjectsIdSprintsSprintIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsIndexRoute
  '/projects/$id/sprints': typeof ProjectsIdSprintsIndexRoute
  '/projects/$id/items/$itemId': typeof ProjectsIdItemsItemIdIndexRoute
  '/projects/$id/settings/templates': typeof ProjectsIdSettingsTemplatesIndexRoute
  '/projects/$id/sprints/$sprintId': typeof ProjectsIdSprintsSprintIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/settings/': typeof ProjectsIdSettingsIndexRoute
  '/projects/$id/sprints/': typeof ProjectsIdSprintsIndexRoute
  '/projects/$id/items/$itemId/': typeof ProjectsIdItemsItemIdIndexRoute
  '/projects/$id/settings/templates/': typeof ProjectsIdSettingsTemplatesIndexRoute
  '/projects/$id/sprints/$sprintId/': typeof ProjectsIdSprintsSprintIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/projects/'
    | '/projects/$id/'
    | '/projects/$id/settings/'
    | '/projects/$id/sprints/'
    | '/projects/$id/items/$itemId/'
    | '/projects/$id/settings/templates/'
    | '/projects/$id/sprints/$sprintId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/projects'
    | '/projects/$id'
    | '/projects/$id/settings'
    | '/projects/$id/sprints'
    | '/projects/$id/items/$itemId'
    | '/projects/$id/settings/templates'
    | '/projects/$id/sprints/$sprintId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/projects/'
    | '/projects/$id/'
    | '/projects/$id/settings/'
    | '/projects/$id/sprints/'
    | '/projects/$id/items/$itemId/'
    | '/projects/$id/settings/templates/'
    | '/projects/$id/sprints/$sprintId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdSettingsIndexRoute: typeof ProjectsIdSettingsIndexRoute
  ProjectsIdSprintsIndexRoute: typeof ProjectsIdSprintsIndexRoute
  ProjectsIdItemsItemIdIndexRoute: typeof ProjectsIdItemsItemIdIndexRoute
  ProjectsIdSettingsTemplatesIndexRoute: typeof ProjectsIdSettingsTemplatesIndexRoute
  ProjectsIdSprintsSprintIdIndexRoute: typeof ProjectsIdSprintsSprintIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/sprints/': {
      id: '/projects/$id/sprints/'
      path: '/projects/$id/sprints'
      fullPath: '/projects/$id/sprints/'
      preLoaderRoute: typeof ProjectsIdSprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/settings/': {
      id: '/projects/$id/settings/'
      path: '/projects/$id/settings'
      fullPath: '/projects/$id/settings/'
      preLoaderRoute: typeof ProjectsIdSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/sprints/$sprintId/': {
      id: '/projects/$id/sprints/$sprintId/'
      path: '/projects/$id/sprints/$sprintId'
      fullPath: '/projects/$id/sprints/$sprintId/'
      preLoaderRoute: typeof ProjectsIdSprintsSprintIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/settings/templates/': {
      id: '/projects/$id/settings/templates/'
      path: '/projects/$id/settings/templates'
      fullPath: '/projects/$id/settings/templates/'
      preLoaderRoute: typeof ProjectsIdSettingsTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/items/$itemId/': {
      id: '/projects/$id/items/$itemId/'
      path: '/projects/$id/items/$itemId'
      fullPath: '/projects/$id/items/$itemId/'
      preLoaderRoute: typeof ProjectsIdItemsItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdSettingsIndexRoute: ProjectsIdSettingsIndexRoute,
  ProjectsIdSprintsIndexRoute: ProjectsIdSprintsIndexRoute,
  ProjectsIdItemsItemIdIndexRoute: ProjectsIdItemsItemIdIndexRoute,
  ProjectsIdSettingsTemplatesIndexRoute: ProjectsIdSettingsTemplatesIndexRoute,
  ProjectsIdSprintsSprintIdIndexRoute: ProjectsIdSprintsSprintIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
