/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects/$id/index'
import { Route as ProjectsIdTemplatesIndexRouteImport } from './routes/projects/$id/templates/index'
import { Route as ProjectsIdItemsItemIdIndexRouteImport } from './routes/projects/$id/items/$itemId/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdTemplatesIndexRoute =
  ProjectsIdTemplatesIndexRouteImport.update({
    id: '/projects/$id/templates/',
    path: '/projects/$id/templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdItemsItemIdIndexRoute =
  ProjectsIdItemsItemIdIndexRouteImport.update({
    id: '/projects/$id/items/$itemId/',
    path: '/projects/$id/items/$itemId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/templates/': typeof ProjectsIdTemplatesIndexRoute
  '/projects/$id/items/$itemId/': typeof ProjectsIdItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/templates': typeof ProjectsIdTemplatesIndexRoute
  '/projects/$id/items/$itemId': typeof ProjectsIdItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/templates/': typeof ProjectsIdTemplatesIndexRoute
  '/projects/$id/items/$itemId/': typeof ProjectsIdItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/projects/'
    | '/projects/$id/'
    | '/projects/$id/templates/'
    | '/projects/$id/items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/projects'
    | '/projects/$id'
    | '/projects/$id/templates'
    | '/projects/$id/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/projects/'
    | '/projects/$id/'
    | '/projects/$id/templates/'
    | '/projects/$id/items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdTemplatesIndexRoute: typeof ProjectsIdTemplatesIndexRoute
  ProjectsIdItemsItemIdIndexRoute: typeof ProjectsIdItemsItemIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/templates/': {
      id: '/projects/$id/templates/'
      path: '/projects/$id/templates'
      fullPath: '/projects/$id/templates/'
      preLoaderRoute: typeof ProjectsIdTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/items/$itemId/': {
      id: '/projects/$id/items/$itemId/'
      path: '/projects/$id/items/$itemId'
      fullPath: '/projects/$id/items/$itemId/'
      preLoaderRoute: typeof ProjectsIdItemsItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdTemplatesIndexRoute: ProjectsIdTemplatesIndexRoute,
  ProjectsIdItemsItemIdIndexRoute: ProjectsIdItemsItemIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
