namespace Eng.Agilium.Be.Exceptions.Validation;

public enum XValidationErrorKey
{
  INVALID_EMAIL_FORMAT = 0,
  INVALID_ADMIN_NAME = 1,
  INVALID_ADMIN_SURNAME = 2,
  INVALID_PASSWORD_FORMAT = 3,
  INVALID_PAGE_INDEX = 101,
  INVALID_TOKEN_FORMAT = 102,
  INVALID_TITLE = 201,
  INVALID_STUDY_NUMBER_FORMAT = 202,
}
